### ISSUE TITLE
Product Categories: The page description or intro text didn't display in front-end

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#102]
![image](https://cloud.githubusercontent.com/assets/12888048/10385319/b3fb6878-6e79-11e5-8d1c-ff0f78c15ad9.png)

**Comment by christiancebudigital** [comment]
this page will only display product category listing, see design attached
![03-hos-product-category](https://cloud.githubusercontent.com/assets/11186331/10473702/0ca0026e-7261-11e5-9272-f9932f259191.jpg)

**Comment by romatitan** [comment]
https://knowledgebase.titanweb.com.au/implementation-practices/page-section-contents/web-copy
![image](https://cloud.githubusercontent.com/assets/12888048/10568245/096fef9c-7648-11e5-9715-86756e66af20.png)
