### ISSUE TITLE
Clarification: Product sidebar button should be static or dynamic? It is not clearly specified in the project scope

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#112]
![image](https://cloud.githubusercontent.com/assets/12888048/10386738/5a1c5de4-6e8d-11e5-9429-f4cb3a98f7ac.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10386740/5c0a00a2-6e8d-11e5-871a-2abd90f41c39.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10386753/74452746-6e8d-11e5-93d1-83dba57122e8.png)

**Comment by christiancebudigital** [comment]
this are all dynamic, acf can be found on this pages
Page - Product Categories ( ACF - file [ Product categories brochure ] )
Post type - woo Product (ACF - file [ Product catalog ])
