### ISSUE TITLE
Clarification: The title above the lead-ins, should it be hardcoded or an ACF is needed? It is not mentioned in the project scope

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#113]
![image](https://cloud.githubusercontent.com/assets/12888048/10386805/f8162b88-6e8d-11e5-8794-b2dbc14d14b0.png)

**Comment by christiancebudigital** [comment]
yep this should be dynamic, updated the site, added new acf label found on homepage.
