### ISSUE TITLE
Clarification - Product Listing: The project scope stated to display a price for product listing page, while in the design, it seems  a product code

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#116]
![image](https://cloud.githubusercontent.com/assets/12888048/10387001/b2e24cca-6e8f-11e5-9693-7b079dd6e8b9.png)

**Comment by christiancebudigital** [comment]
Yes it think this is an product sku, but i have no control over the Project scope on this one.
