### ISSUE TITLE
Banner: The overlay was too dark compared to what the design has.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#12]
![image](https://cloud.githubusercontent.com/assets/12888048/9950569/823d6cb4-5dee-11e5-8250-33e8dbb130f9.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

Images used have blackbg, causing to double the effect bg overlay, resulting darker design. uploaded new images.

Thanks,
Christian
