### ISSUE TITLE
Services: 'BACK TO TOP' button, once click it will jump instantly to the top of the page. The project scope stated to have a smooth scrolling effect.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#121]
![image](https://cloud.githubusercontent.com/assets/12888048/10387951/39623f5a-6e98-11e5-8cdd-d1228f673125.png)

**Comment by romatitan** [comment]
Reference:
https://css-tricks.com/examples/SmoothPageScroll/

**Comment by christiancebudigital** [comment]
Please clear cache working in my end.

**Comment by romatitan** [comment]
Kindly check again.
Reference:
https://css-tricks.com/examples/SmoothPageScroll/
