### ISSUE TITLE
Products: The font-family, weight, size and color for download button label was set to RobotoRegular, 14px and #0088cf. It should be Exo, Black, 18px and #003956

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#133]
Product Categories page - Download Category Brochure button
Product Listing page - Download Category Brochure button
Product Single page  Download Product Catalouge button

![image](https://cloud.githubusercontent.com/assets/12888048/10420070/abaadd18-70bb-11e5-9c41-8d45521fb67e.png)

**Comment by christiancebudigital** [comment]
this is a static image
