### ISSUE TITLE
Product Single: Font-family and size for "CONTACT US TODAY" button label was set to Roboto and 14px. It should be Exo and 18px.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#138]
![image](https://cloud.githubusercontent.com/assets/12888048/10420120/345448f6-70bd-11e5-8506-af56ceb42acf.png)

**Comment by christiancebudigital** [comment]
this is an image

**Comment by romatitan** [comment]
Button label has serif, and font-weight was set to semi-bold.
It should be black.

![image](https://cloud.githubusercontent.com/assets/12888048/10628979/48b56f36-77fd-11e5-9bf1-14efc5f696ea.png)

**Comment by romatitan** [comment]
@christiancebudigital 
Button label has serif, and font-weight was set to semi-bold.
It should be black.

![image](https://cloud.githubusercontent.com/assets/12888048/10686838/b94c8092-799a-11e5-92dd-b13c3c3d241d.png)
