### ISSUE TITLE
The sidebar on the page has seem no space on the right side after re-sizing the browser

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#154]
around W:1058px
![image](https://cloud.githubusercontent.com/assets/12888048/10571682/f52f83e0-7673-11e5-861e-c4682d708cce.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10571683/f7855d2c-7673-11e5-9351-a438096b8924.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10571685/f97893f6-7673-11e5-831d-e5298fbbda6b.png)

**Comment by christiancebudigital** [comment]
this will have no padding because, this is a sticky sidebar, the position here is fixes, this is the plugin we used based on the notes given. http://spoiledmilk.com/demos/sticky-sidebar/

**Comment by romatitan** [comment]
If that's the case, then, it will be better to place the sidebar at the bottom

**Comment by christiancebudigital** [comment]
Will this be an enhancement?

**Comment by romatitan** [comment]
I've updated the bug description and please see the attached link for reference.
http://accentgranite.stage.titanweb.com.au/our-services/

**Comment by romatitan** [comment]
It seems the same with #171
