### ISSUE TITLE
Homepage: Truncated page description

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#158]
![image](https://cloud.githubusercontent.com/assets/12888048/10630999/669cf216-780d-11e5-9a47-2e909dde2624.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10631002/69b0061e-780d-11e5-828a-14381a6d3b8a.png)

**Comment by romatitan** [comment]
Still reproducible on S4 and ipodtouch5 device

**Comment by christiancebudigital** [comment]
please clear cache, see what my i have in my end.
![home](https://cloud.githubusercontent.com/assets/11186331/10812331/0a260344-7e50-11e5-8c8c-cce0c29ca059.jpg)

**Comment by romatitan** [comment]
Not yet fix on S4 and iPod touch5

**Comment by romatitan** [comment]
not yet fix on S4

**Comment by romatitan** [comment]
not yet fix on S4
