### ISSUE TITLE
Contact us: Page content has not been added.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hose-Force-Re-Check#16]
![image](https://cloud.githubusercontent.com/assets/11186313/9950673/8d8c1ede-5def-11e5-99c7-94c6ae643c8f.png)

**Comment by christiancebudigital** [comment]
Hi Roselie,

Would it be ok to attach the file here, as i don't file in my end.

Thanks,
Christian

**Comment by romatitan** [comment]
[Hose Force_WebCopy_FINAL.docx](https://github.com/titan-cebu/Hose-Force-Re-Check/files/9852/Hose.Force_WebCopy_FINAL.docx)
