### ISSUE TITLE
Gallery - devices: It seems there's a truncated element on the right side of the album

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#169]
Affected device(s): S4, ipodtouch5, ipadair

![image](https://cloud.githubusercontent.com/assets/12888048/10653869/6a4d2b0e-7896-11e5-9d9c-0a31f76a39e6.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10653872/6c55e9ae-7896-11e5-90b2-55e32da58d9f.png)

**Comment by christiancebudigital** [comment]
Hi Roma, Ive attached here
![smalldevice](https://cloud.githubusercontent.com/assets/11186331/10811711/e1bbf702-7e49-11e5-9831-a21ec090d4f9.jpg) my screenshot. please clear cache...
