### ISSUE TITLE
Banner - devices: Our Products section in the banner is missing in devices

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#173]
![image](https://cloud.githubusercontent.com/assets/12888048/10688372/80a26d7c-79a6-11e5-9218-5dac6bde3c6b.png)

**Comment by christiancebudigital** [comment]
this was remove because it cant be fit in the banner, any suggestions on where to put it?

**Comment by romatitan** [comment]
If the content (title, description, Our, products, list of products) can't fit in the banner, placed it under the banner

**Comment by romatitan** [comment]
If the content (title, description, Our, products, list of products) can't fit in the banner, placed it under the banner
Kindly apply this as well in  S4 and ipodtouch5.
