### ISSUE TITLE
Product Listing: The "View More" button is smaller compared to what the design has, the inclination is different as well.  It has a width and height of approximately W:123px, H:47px. In the given design, it has W:149px and H:51px.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#193]
![image](https://cloud.githubusercontent.com/assets/12888048/10900473/3522fbe6-821b-11e5-99b4-e97c7a0e90ee.png)

**Comment by romatitan** [comment]
Kindly check again the width of the button.
Current width is approximately 169px.
In the given design, it has 149px, thus a difference of 20px.

**Comment by christiancebudigital** [comment]
please clear cache, this is is skewed css, see style css, thus overpowering the css width.
