### ISSUE TITLE
News: The "Read More" button has a width and height of approximately W:117px, H:51px. The inclination is different as well. In the give design it has W:129px and H:44px

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#199]
![image](https://cloud.githubusercontent.com/assets/12888048/10900928/319f45be-8221-11e5-8f02-c44cdf8d673e.png)

**Comment by romatitan** [comment]
Kindly check again the width of the button, it has an approximately W:157px

**Comment by christiancebudigital** [comment]
please clear cache, please dont measure this as pixel per pixel, this was already addressed by jo, this is a skewed css box.
