### ISSUE TITLE
Contact us: There are extra bullets beside the fields.  They should be removed and have the form fields aligned with the page title.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hose-Force-Re-Check#2]
![image](https://cloud.githubusercontent.com/assets/11186313/9950010/0f3c6158-5de8-11e5-8601-06fed3c993de.png)

**Comment by romatitan** [comment]
form fields should be aligned with the page title
![image](https://cloud.githubusercontent.com/assets/12888048/10358944/1a5fa232-6dc6-11e5-8eed-c21613ddb22d.png)
