### ISSUE TITLE
Product Single: The product featured image width and height have an approximately W:308px and H:205px In the given design, it has W:334px and H:243px

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#220]
![image](https://cloud.githubusercontent.com/assets/12888048/10987656/4a2348a0-8470-11e5-9374-679f619bb691.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/11025426/b1026670-86d5-11e5-8674-cd0ed3c5f5f8.png)

**Comment by romatitan** [comment]
Kindly check again the height of the image

**Comment by christiancebudigital** [comment]
see attached image.
![test](https://cloud.githubusercontent.com/assets/11186331/11056972/2103431c-87c2-11e5-8974-962f02020c6f.jpg)
