### ISSUE TITLE
Product Single: Product description wasn't aligned with the top edge of the image

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#223]
@christiancebudigital 
Please, kindly check the Product single page.
The product featured image, thumbnails, buttons and content

![image](https://cloud.githubusercontent.com/assets/12888048/10988352/8da69a40-8476-11e5-90a3-51afba6b449d.png)

**Comment by romatitan** [comment]
Kindly check again as well as in mobile devices.

![image](https://cloud.githubusercontent.com/assets/12888048/11260606/c562f1a0-8ea7-11e5-8b74-89c43359879b.png)


S4 & iPodtouch5
![image](https://cloud.githubusercontent.com/assets/12888048/11260593/aad71550-8ea7-11e5-8c0d-43c10560fbaa.png)

iPad Air
![image](https://cloud.githubusercontent.com/assets/12888048/11260603/b927c168-8ea7-11e5-9c1a-2cf566f38c44.png)

**Comment by christiancebudigital** [comment]
https://knowledgebase.titanweb.com.au/wordpress/e-commerce/woocommerce-product-images

**Comment by romatitan** [comment]
Product description was aligned with the image container
