### ISSUE TITLE
Lead-ins - device: Lead-in overlaps the welcome content

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#234]
Affected device(s): S4 
![image](https://cloud.githubusercontent.com/assets/12888048/11053744/a0f43a5a-879e-11e5-98ea-77e88466f52f.png)

**Comment by christiancebudigital** [comment]
this is ok in our end. please clear cache

**Comment by romatitan** [comment]
Kindly check it again on S4 device
