### ISSUE TITLE
Services Quicklinks Sidebar - devices: The sidebar overlaps the page content and contact us today button.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#235]
Affected device(s): S4, iPodtouch5

Step to Reproduce:
1. On device portrait view, scroll down until the it reaches the sidebar 
2. Then rotate the view to landscape.

![image](https://cloud.githubusercontent.com/assets/12888048/11053781/fb66ca3e-879e-11e5-94df-081a8f359492.png)

**Comment by christiancebudigital** [comment]
please clear cache, it is ok in our end.
