### ISSUE TITLE
Services: Custom post featured image height is approximately H:127px. In the given design it has 143px, thus a difference of 16px.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#236]
![image](https://cloud.githubusercontent.com/assets/12888048/11054232/5bac3384-87a4-11e5-8b22-adc31562fd5c.png)

**Comment by christiancebudigital** [comment]
uploade bigger image, so that it will regenerate new image that will fit on th desired height.

**Comment by romatitan** [comment]
This is the sample image for testing with the size of 3504 × 2336
![image](https://cloud.githubusercontent.com/assets/12888048/11110177/cf909a3e-8933-11e5-82ea-48440eae7506.png)

![image](https://cloud.githubusercontent.com/assets/12888048/11110229/439711d8-8934-11e5-9235-ffc6cc285765.png)

The post featured image should be display the same with what the design has.
![image](https://cloud.githubusercontent.com/assets/12888048/11110253/74feb3d4-8934-11e5-95f7-45fa21be9c25.png)
