### ISSUE TITLE
Product Categories: Subcategories did not display in front-end. It should be displayed and styled the same with the main category page

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#249]
![image](https://cloud.githubusercontent.com/assets/12888048/11177883/be4d8964-8c83-11e5-8e81-4a0a58c4f176.png)

**Comment by christiancebudigital** [comment]
in order to display the newly added category, this should have a post. see attached.
![test](https://cloud.githubusercontent.com/assets/11186331/11200120/269e9668-8d0e-11e5-933a-f03e92a2064a.jpg)
