### ISSUE TITLE
Product Listing: Page has no Load More function (It was implemented before)

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#256]

**Comment by christiancebudigital** [comment]
according to harold, sub category can be paginated.. not the products category..

**Comment by romatitan** [comment]
I update the bug title. It's Product Listing.
![image](https://cloud.githubusercontent.com/assets/12888048/11259115/e2962818-8e99-11e5-92ea-cc38aaadc44a.png)
