### ISSUE TITLE
Product Single: Inconsistent size of container for product featured image

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#263]
![image](https://cloud.githubusercontent.com/assets/12888048/11260661/4abb8baa-8ea8-11e5-9f5c-00f04aba3497.png)

**Comment by christiancebudigital** [comment]
http://hoseforce.stage.titanweb.com.au/wp-content/uploads/2015/10/image-sample.jpg
please upload bigger image, this is to prevent image to be not stretch.
https://knowledgebase.titanweb.com.au/wordpress/e-commerce/woocommerce-product-images
