### ISSUE TITLE
Services page: Post titles aren't linked to its associative posts.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hose-Force-Re-Check#29]
![image](https://cloud.githubusercontent.com/assets/11186313/9951403/8d869546-5df8-11e5-9375-9af1b8305bbd.png)

![image](https://cloud.githubusercontent.com/assets/11186313/9951393/808bad90-5df8-11e5-8097-37e6fc71f84e.png)

**Comment by romatitan** [comment]
Post title in the sidebar, once click it will open the post to a single page.
" It should take the user to its associative post using smooth scroll functionality." as what the project scope has stated
