### ISSUE TITLE
News single page: Font family for the breadcrumbs should be exo medium.  Current font used is roboto regular.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hose-Force-Re-Check#34]

**Comment by romatitan** [comment]
The font-family set was Exo Medium but  it seems the font was different from what the design has.
It seems that it didn't define the "Medium" font weight.

![image](https://cloud.githubusercontent.com/assets/12888048/10360094/afe868ac-6dd0-11e5-9b8f-9988e2c6a4a2.png)

**Comment by christiancebudigital** [comment]
for your reference, you can see the defined font style
![a](https://cloud.githubusercontent.com/assets/11186331/10422875/0053f2d2-70f3-11e5-8eb7-03bf14146249.jpg)

**Comment by romatitan** [comment]
Then, kindly check again why the font displayed in the front-end was different compared to what the design has. Please check the screenshot above.

**Comment by christiancebudigital** [comment]
i think the issue here is the font size, updated the site, please clear cache, thanks.

**Comment by romatitan** [comment]
I cleared the cache before checking this.
Kindly check again.

**Comment by christiancebudigital** [comment]
![aaaa](https://cloud.githubusercontent.com/assets/11186331/10681907/3f97574c-7961-11e5-8040-66531eeaafe1.jpg)
this is what my end looks like..

**Comment by romatitan** [comment]
Same here.
The font was set to Exo Medium, but seems different in the design.

![image](https://cloud.githubusercontent.com/assets/12888048/10686223/7235bd8c-7994-11e5-9783-d7c2a5a98657.png)
