### ISSUE TITLE
News sidebar title should have exo demibold font weight.  Current font weight used is exo regular.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hose-Force-Re-Check#51]
![image](https://cloud.githubusercontent.com/assets/11186313/9952656/dc6c5382-5e0a-11e5-957b-ce0a76d3a15e.png)

**Comment by romatitan** [comment]
Text has serif.
It seems that "Semibold" font weight wasn't defined
![image](https://cloud.githubusercontent.com/assets/12888048/10360839/9c527dc2-6dd6-11e5-804d-a11e18b9436b.png)
