### ISSUE TITLE
Footer section: Discrepancy in the SEO footer.  It is not clear as to which footer ranking to be used.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hose-Force-Re-Check#6]
![image](https://cloud.githubusercontent.com/assets/11186313/9950371/7931859e-5dec-11e5-81bd-c6d659ee0acf.png)

**Comment by romatitan** [comment]
SEO footer implemented did not match to the option 1 mentioned in the project scope
![image](https://cloud.githubusercontent.com/assets/12888048/10359013/de7beed2-6dc6-11e5-9756-bdcfd9078a13.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10359016/e03c2dea-6dc6-11e5-80ce-fbb95bfe6023.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10359025/0550294c-6dc7-11e5-8ce1-c5568af6e38d.png)
