### ISSUE TITLE
News page: Content isn't limited to 3 lines.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hose-Force-Re-Check#75]
IE browser only
![image](https://cloud.githubusercontent.com/assets/11186313/9955856/b65c3038-5e26-11e5-88f6-54dda8e53d94.png)

**Comment by romatitan** [comment]
If a post has featured image, only 2 lines of the post description was displayed.
Number of lines will depend on the design. Allow the description up to 3 lines as what the design has.

Reference:
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/post-title-and-post-desription
