### ISSUE TITLE
Thank you page: Font color isn't consistent with other pages.  Other pages used #7979779 while in this page, font color used is #444.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Hose-Force-Re-Check#8]
![image](https://cloud.githubusercontent.com/assets/11186313/9950419/f6619d88-5dec-11e5-81ac-b1407845cbdb.png)

**Comment by romatitan** [comment]
Font color should not be set as !important.
![image](https://cloud.githubusercontent.com/assets/12888048/10359189/b82c38de-6dc8-11e5-9b98-034a5b91a87c.png)
