### ISSUE TITLE
News Single - devices: Post item was centered. It should be left aligned.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#87]
![image](https://cloud.githubusercontent.com/assets/12888048/9956403/12cbf5ac-5e2b-11e5-8492-528581d40782.png)

**Comment by romatitan** [comment]
Kindly check again in device (s4, ipodtouch, ipadair) portrait view.

**Comment by romatitan** [comment]
Kindly check again in device (s4, ipodtouch) portrait view.

**Comment by christiancebudigital** [comment]
please clear cache, it is working on our end.

**Comment by romatitan** [comment]
Kindly check again in device (s4, ipodtouch) portrait view.
