### ISSUE TITLE
Header: The navigation menus was stretched (upward) when hovering over the About Us menu and post in the sidebar

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Hose-Force-Re-Check#93]
![image](https://cloud.githubusercontent.com/assets/12888048/10384955/59c2e6f0-6e75-11e5-8d8a-44b5f7bfa8fe.png)

**Comment by christiancebudigital** [comment]
What do we mean by " post in the sidebar "?

**Comment by romatitan** [comment]
These,
![image](https://cloud.githubusercontent.com/assets/12888048/10627431/e1accfca-77eb-11e5-8ef2-e0b9a0593870.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10627432/e3b26438-77eb-11e5-9462-658b9bc92c39.png)
![image](https://cloud.githubusercontent.com/assets/12888048/10627433/e69be714-77eb-11e5-834e-225ba5c5500f.png)

**Comment by romatitan** [comment]
Kindly check again.
1. Homepage : Hover the mouse at the "About Us" menu
2. Sidebar: Hover on any post in the sidebar
( Our Products Sidebar, Services Quicklinks Sidebar, Latest News Sidebar)
